# Generated by Django 4.1.4 on 2023-09-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_wallet_bonus_balance_alter_businesslogs_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwithdrawls",
            name="bonus_amount",
            field=models.CharField(default="250", max_length=250),
        ),
        migrations.AddField(
            model_name="userwithdrawls",
            name="direct_amount",
            field=models.CharField(default="0", max_length=250),
        ),
        migrations.AddField(
            model_name="userwithdrawls",
            name="level_amount",
            field=models.CharField(default="0", max_length=250),
        ),
        migrations.AddField(
            model_name="userwithdrawls",
            name="roi_amount",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="businesslogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 183759), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="changesponserlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 183759), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="farmingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 184736), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="levelincome",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 186746), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="newsmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 185741), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="ptransfer",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 188746), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="stakingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 185741), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="status_activity",
            name="time",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 187780), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 186746), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 181766), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 181766), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usercofounderclub",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 189745), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 184736), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="userrank",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 189745), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 188746), max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userstaking",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 184736), max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="userwithdrawls",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 6, 12, 1, 0, 187780), max_length=200
            ),
        ),
    ]
