# Generated by Django 4.1.4 on 2023-09-11 14:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_user_business_balance_alter_businesslogs_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rewards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(max_length=250)),
                ("income", models.CharField(max_length=250)),
                ("business_required", models.CharField(max_length=250)),
                ("days", models.CharField(max_length=250)),
                ("status", models.CharField(default="1", max_length=250)),
            ],
            options={
                "db_table": "rewards",
            },
        ),
        migrations.AlterField(
            model_name="businesslogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 374170),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="changesponserlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 390122),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="farmingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="levelincome",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newsmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ptransfer",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stakingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="status_activity",
            name="time",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 374170),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 374170),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usercofounderclub",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userrank",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userstaking",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userwithdrawls",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 14, 59, 15, 391227),
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="userRewards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reward_recieved", models.CharField(default="0", max_length=200)),
                ("status", models.CharField(default="0", max_length=100)),
                (
                    "date",
                    models.CharField(
                        default=datetime.datetime(2023, 9, 11, 20, 29, 15, 391227),
                        max_length=200,
                    ),
                ),
                (
                    "club_id",
                    models.ForeignKey(
                        db_column="club_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cofounderclub",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "userrewards",
            },
        ),
    ]
