# Generated by Django 4.1.4 on 2023-09-11 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_rewards_alter_businesslogs_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrewards",
            name="club_id",
        ),
        migrations.AddField(
            model_name="userrewards",
            name="rank_id",
            field=models.ForeignKey(
                db_column="rank_id",
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.rewards",
            ),
        ),
        migrations.AlterField(
            model_name="businesslogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="changesponserlogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="farmingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="levelincome",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 288563),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newsmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ptransfer",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 288563),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="stakingroilogs",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="status_activity",
            name="time",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 288563),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="ticketmodel",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 288563),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usercofounderclub",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 292071),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="usermembership",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userrank",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 292071),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 288563),
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userrewards",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 21, 4, 23, 292071),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userstaking",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 272939),
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userwithdrawls",
            name="date",
            field=models.CharField(
                default=datetime.datetime(2023, 9, 11, 15, 34, 23, 288563),
                max_length=200,
            ),
        ),
    ]
