from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('dashboard',views.home), 
    path('dashboard/<str:pk>/',views.home),   
    path('users',views.userdata),
    path('users/<str:pk>/',views.userdata),
    path('levels',views.levelsview),
    path('signout',views.signout),
    path('myprofile',views.userprofile),
    path('get_refferal/<str:pk>/',views.get_reffer_data),
    path('emailsettings',views.emailsettings),
    path('emailsettings/<str:pk>/',views.emailsettings),
    path('paid',views.verified_users),
    path('unpaid',views.unpaid_users),
    path('active',views.active),
    path('inactive',views.inactive),
    path('revenue',views.revenue),
    path('packages',views.packages),
    path('packages/<str:pk>/',views.packages),
    path('referral_users',views.referral_users),
    path('withdraw_history',views.withdraw_history),
    path('withdraw_manage',views.withdraw_manage),
    path('membership',views.membership_list),
    path('ticket',views.ticket),
    path('ticket_history',views.ticket_history),
    path('withdraw_settings',views.withdraw_settings),
    path('invest_log',views.invest_log),
    path('refferal_log',views.refferal_log),
    path('transaction_log',views.transaction_log),
    path('login_log',views.login_log),
    path('plans',views.allplans),
    path('app',views.general_settings),
    path('events',views.eventsview),
    path('staking',views.staking),
    path('roihistory',views.roihistory),
    path('stakingroihistory',views.stakingroihistory),
    path('gallery',views.gallery),
    path('deposite_manage',views.deposite_manage),
    path('deposite_history',views.deposite_history),
    path('internal_transfer',views.internal_transfer),
    path('ytvedio',views.ytvideo),
    path('rank',views.rank),
    path('club',views.cofounder),
    path('userrank',views.user_rank),
    path('clubhistory',views.clubhistory),
    path('addfund',views.addfund),
    path('addfund/<str:pk>/',views.addfund),
    path('admin_login',views.admin_login),
    path('admin_login/<str:pk>/',views.admin_login),
    path('manageroi',views.manageroi),
    path('manageroi/<str:pk>/',views.manageroi),
    path('manageuserroi',views.manageuserroi),
    path('smart_contract',views.smart_contract),
    path('topup_history',views.topup_history),
    path('change_sponser',views.change_sponser),
    path('level_income',views.level_income),
    path('tree/<str:pk>/',views.tree)
   

]
